[0m22:33:11.090271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C8E53AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C9550C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C9550B30>]}


============================== 22:33:11.110177 | a1c5daa5-caae-4563-b69d-72a3e0c77a8e ==============================
[0m22:33:11.110177 [info ] [MainThread]: Running with dbt=1.8.5
[0m22:33:11.110177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcelo.passos\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_banks_info', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:33:11.172564 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/marcelo.passos/.dbt')}
[0m22:33:11.172564 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:33:11.182463 [debug] [MainThread]: Starter project path: C:\Users\marcelo.passos\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m22:33:11.271634 [info ] [MainThread]: 
Your new dbt project "dbt_banks_info" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:33:11.276701 [info ] [MainThread]: Setting up your profile.
[0m22:33:11.280383 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:33:11.285416 [debug] [MainThread]: Command `dbt init` failed at 22:33:11.285416 after 0.46 seconds
[0m22:33:11.285416 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C9C2B440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C9C8A180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161C9E39850>]}
[0m22:33:11.290408 [debug] [MainThread]: Flushing usage events
[0m23:45:37.869164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D26E1FE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D23CA1070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D273FC230>]}


============================== 23:45:37.879734 | c9cbdaed-9820-4417-bdb3-96d83975bea3 ==============================
[0m23:45:37.879734 [info ] [MainThread]: Running with dbt=1.8.5
[0m23:45:37.884736 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marcelo.passos\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:45:37.887079 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marcelo.passos\Desktop\P√≥s Poli\Ingest√£o\Ingestao_by_python\DATA INGESTION\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:45:37.892849 [debug] [MainThread]: Command `dbt run` failed at 23:45:37.892849 after 0.33 seconds
[0m23:45:37.892849 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D2779B2C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D2733B980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024D273393D0>]}
[0m23:45:37.897886 [debug] [MainThread]: Flushing usage events
